CREATE TABLE CONTAINS_PRODUCT (
    ID INT PRIMARY KEY,
    CART_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    QUANTITY INT
);

INSERT INTO CONTAINS_PRODUCT VALUES(1, 100, 1000, 2);
INSERT INTO CONTAINS_PRODUCT VALUES(2, 100, 1001, 3);