--Create customer table
CREATE TABLE CUSTOMER (
    ID INT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    ADDRESS VARCHAR(255),
    PHONE VARCHAR(255),
    EMAIL VARCHAR(255),
    PASSWORD VARCHAR(255),
    BIRTHDATE VARCHAR(255)
);

--Create table of carts
CREATE TABLE CART (
  CARTID INT PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL,
  DESCRIPTION VARCHAR(255),
  CART_OWNER_ID INT
);

--Create table of products
CREATE TABLE PRODUCT (
  ID INT PRIMARY KEY,
  NAME VARCHAR(255),
  DESCRIPTION VARCHAR(255),
  MANUFACTURER VARCHAR(255)
);

--Create table of orders
CREATE TABLE ORDERS (
  ID INT PRIMARY KEY,
  READY_DATE VARCHAR(255),
  DELIVERY_OR_PICKUP VARCHAR(255),
  FULFILLED VARCHAR(255),
  COST INT
);